# -------------------------------------------------------------------
# mock_client.py
# Mock LLM client for testing without hitting a real API.
# Returns deterministic responses based on the prompt content.
# -------------------------------------------------------------------

import hashlib
import logging
from typing import Dict, Any

from src.llm.llm_client import LlmClient
from src.models.llm_request import LlmRequest
from src.models.llm_response import LlmResponse

# Module-level logger for mock client operations
logger = logging.getLogger(__name__)


class MockLlmClient(LlmClient):
    """Mock LLM client for testing and demonstration purposes.

    Returns deterministic responses based on the prompt content,
    simulating LLM behavior without requiring an API key or network.

    Attributes:
        default_model: The model name to report in responses.
        call_count: Number of requests processed by this mock client.
    """

    def __init__(self, llm_config: Dict[str, Any] = None):
        """Initialize the mock LLM client.

        Args:
            llm_config: Optional configuration dictionary (ignored for mock).
        """
        self.default_model = "mock-gpt-4"  # Identifier for mock responses
        self.call_count = 0  # Track number of calls for verification

        logger.info("Mock LLM client initialized")

    def send_request(self, request: LlmRequest) -> LlmResponse:
        """Generate a deterministic mock response for the given request.

        Creates a response based on the prompt content hash to ensure
        consistent outputs for the same input during testing.

        Args:
            request: The LlmRequest containing the prompt.

        Returns:
            An LlmResponse with mock-generated content.
        """
        # Increment the call counter
        self.call_count += 1

        # Generate a deterministic response based on prompt hash
        prompt_hash = hashlib.md5(request.prompt.encode()).hexdigest()[:8]
        response_content = (
            f"Mock response for prompt (hash: {prompt_hash}): "
            f"This is a simulated LLM response to '{request.prompt[:50]}...'. "
            f"In a production environment, this would be generated by the actual model."
        )

        # Simulate token counts based on text lengths
        prompt_tokens = len(request.prompt.split())
        completion_tokens = len(response_content.split())

        # Build the mock response object
        response = LlmResponse(
            content=response_content,
            model=self.default_model,
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            total_tokens=prompt_tokens + completion_tokens,
            cached=False,
        )

        logger.info(
            "Mock response generated (call #%d, tokens: %d)",
            self.call_count,
            response.total_tokens,
        )

        return response
