# -------------------------------------------------------------------
# main.py
# Entry point for the LLM Caching application.
# Demonstrates the caching functionality with example prompts.
# -------------------------------------------------------------------

import sys
import logging

from src.config_loader import ConfigLoader
from src.logger_setup import setup_logging
from src.llm_cache_service import LlmCacheService
from src.models.llm_request import LlmRequest

# Module-level logger for main application flow
logger = logging.getLogger(__name__)


def run_demo():
    """Run a demonstration of the LLM caching system.

    Sends multiple prompts including similar ones to showcase
    cache hit behavior for both syntactic and semantic matches.
    """
    # Load application configuration
    config = ConfigLoader()

    # Set up logging based on configuration
    setup_logging(config.get_section("logging"))

    logger.info("=== LLM Cache Demo Starting ===")

    # Initialize the LLM cache service
    service = LlmCacheService(
        cache_config=config.get_section("cache"),
        similarity_config=config.get_section("similarity"),
        llm_config=config.get_section("llm"),
    )

    # Define demo prompts - includes similar prompts to trigger cache hits
    demo_prompts = [
        # First request - will be a cache miss (new prompt)
        "What is machine learning and how does it work?",
        # Second request - syntactically similar (minor rephrasing)
        "What is machine learning and how does it work",
        # Third request - semantically similar (different words, same meaning)
        "Explain how machine learning works and what it is",
        # Fourth request - completely different (cache miss)
        "What are the best practices for REST API design?",
        # Fifth request - semantically similar to fourth
        "Tell me about REST API design best practices",
        # Sixth request - exact repeat of first (syntactic hit)
        "What is machine learning and how does it work?",
    ]

    print("\n" + "=" * 70)
    print("  LLM CACHING DEMONSTRATION")
    print("  Showing syntactic and semantic similarity cache behavior")
    print("=" * 70 + "\n")

    # Process each prompt and display results
    for index, prompt in enumerate(demo_prompts, start=1):
        print(f"\n--- Request #{index} ---")
        print(f"Prompt: {prompt}")
        print("-" * 50)

        # Create the LLM request object
        request = LlmRequest(prompt=prompt)

        # Process through the caching service
        response = service.process_request(request)

        # Display the response details
        if response.cached:
            print(f"  [CACHE HIT] Match type: {response.metadata.get('match_type', 'unknown')}")
            print(f"  Similarity score: {response.similarity_score:.4f}")
            print(f"  Original cached prompt: {response.metadata.get('original_prompt', 'N/A')[:60]}...")
        else:
            print(f"  [CACHE MISS] Response generated by LLM")
            print(f"  Tokens used: {response.total_tokens}")

        print(f"  Response preview: {response.content[:80]}...")

    # Display final statistics
    stats = service.get_stats()
    print("\n" + "=" * 70)
    print("  CACHE STATISTICS")
    print("=" * 70)
    print(f"  Total requests:  {stats['total_requests']}")
    print(f"  Cache hits:      {stats['cache_hits']}")
    print(f"  Cache misses:    {stats['cache_misses']}")
    print(f"  Hit rate:        {stats['hit_rate_percent']:.1f}%")
    print(f"  Cached entries:  {stats['total_entries']}")
    print("=" * 70 + "\n")


def run_server():
    """Start the FastAPI server for REST API access."""
    import uvicorn

    # Load configuration for server settings
    config = ConfigLoader()
    server_config = config.get_section("server")

    # Extract host and port from configuration
    host = server_config.get("host", "0.0.0.0")
    port = server_config.get("port", 8000)

    print(f"\nStarting LLM Cache API server on {host}:{port}")
    print("API docs available at: http://localhost:{port}/docs\n")

    # Start the uvicorn ASGI server
    uvicorn.run("src.api:app", host=host, port=port, reload=False)


if __name__ == "__main__":
    # Determine run mode from command line arguments
    if len(sys.argv) > 1 and sys.argv[1] == "--server":
        # Start in API server mode
        run_server()
    else:
        # Run the demo by default
        run_demo()
